X = [0:15]
Y = [0:15]
Strain = zeros(length(X));
Relief = Strain;
Roll = Strain;
Normal = Strain;
Weight = Strain;
TestFunc = Strain;
for x = X
    for y = Y
        Strain(x+1,y+1) = (max(x,y)-min(x,y));
        Relief(x+1,y+1) = Strain(x+1,y+1)/(min(x,y)+1);
        Roll(x+1,y+1) = 1/(1+Relief(x+1,y+1));
        Ramp(x+1,y+1) = 1/(x+y+1);
        Normal(x+1,y+1) = (2*Relief(x+1,y+1) + 1)^1/2;
        Weight(x+1,y+1) = ((((Relief(x+1,y+1)*Strain(x+1,y+1)*Roll(x+1,y+1))^2)/Normal(x+1,y+1))^(1/2))
        NewWeight(x+1,y+1) = ((((Relief(x+1,y+1)*Strain(x+1,y+1)*Roll(x+1,y+1))^2)/Normal(x+1,y+1))^(1/2))*Ramp(x+1,y+1)
        %NewWeight(x+1,y+1) = NewWeight(x+1,y+1) +0.1*(Roll(x+1,y+1))
        NewWeight(x+1,y+1) = ((((Relief(x+1,y+1)*Strain(x+1,y+1)*Roll(x+1,y+1))^2)/Normal(x+1,y+1))^(1/2))*Ramp(x+1,y+1)
        NewWeight(x+1,y+1) = (NewWeight(x+1,y+1)+0.2*(Ramp(x+1,y+1))+1) %.^2
        TestFunc(x+1,y+1) = (NewWeight(x+1,y+1)-1)
        %Weight(x+1,y+1) = Weight + 0.2*(x^(1/2)+y^(1/2));
        %NewWeight(x+1,y+1) = ((((Relief(x+1,y+1)*Strain(x+1,y+1)*Roll(x+1,y+1)*Ramp(x+1,y+1))^2)/Normal(x+1,y+1)))
    end
end
%%
RollInv = 1./Roll
NewWeight = (1+Weight).^(1/2)

function [fitresult, gof] = createFit1(X, Y, NewWeight)
%CREATEFIT1(X,Y,NEWWEIGHT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: NewWeight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Aug-2019 15:43:45


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X, Y, NewWeight );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Bulge length mismatch vs. weight' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'NewWeight vs. X, Y', 'Location', 'NorthEast' );
% Label axes
xlabel Bulge-A
ylabel Bulge-B
zlabel Bulge Weight
grid on
view( -45.9, 14.8 );