
maxlength = 300
minsubHPlength = 3 #HPs <=3 will be substituted
subHPlength = 6  #will be replaced with HPs of len <


# Shooting Star
Name = 'ShootingStar'
SS_Goal = '(((((((((((((((((...(.(..((.(((.(((.((....).))).)))).).)..))..))))))).(((((..(.(..((.(((.(((((.(((.((((.((....).)))).))))).))).)))).).)..))..)(....)..))))(((((((((...))))).(((((...)))))(.(....).).)))).)))).((((.((((...(((((((...))))))).(((((...)))))))))(((((((...))))))).(((((...)))))))))((((..(....)(..(..(..(.(.(((.((((.((....).)))).)))).)..)..).)..))))).)))))).'
PS_Goal = 'UAUAUGCCCCCUAUAUCGAAGAUUGACGCUGACCGACCGAAAGCGCGCGCAGGGAUUGACGAGAUAUAGACCCAGUGGAUUGCCGUAGACCAGCGCCGACCAGACCGAAAGCGCUGCGCGGGACUGCGCUAGGAGUGACUGCCGAAAGAAUGGGGGCCGUAUGAAACAUACACUAUGAAACAUAGCGGGAAACGGAGGCCAGGGGAUCCCAGGACAAGUAUAUACAAAGUAUAUAACAUAGAAACUAUGGUCCGUAUAUAAAAUAUAUACAAUACGAAACGUAUGGGAGCGGAACGAAAGGUGGGGCUGCACGGAGACCAGACCGAAAGCGCUGCGCUCGGGGGUGGACUGCCCGCACAUAUAA'

## Teslagon
SS_Goal = '......((.......((.((.......((.((...............)).........((...............)).)).......)).((.......((...............)).......)).((.......((.((...............)).........((...............)).)).......)).((.......((...............)).......)).((.......((.((...............)).........((...............)).)).......)).((.......((............((...............)).)).......)).)).......))......'
PS_Goal = 'AAAAAAGAGAAAAAGCCAGCGAAAAAAGGAGGGAAAAAAAAAAAAAACCAAAAAAAAAGCGAAAAAAAAAAAAAAGCACCGAAAAAAGCAGCGAAAAAAGGGAAAAAAAAAAAAAACCGAAAAAAGCAGGGAAAAAAGCAGGGAAAAAAAAAAAAAACCAAAAAAAAAGCGAAAAAAAAAAAAAAGCAGCGAAAAAACCAGGAAAAAAGCCGAAAAAAAAAAAAAAGGAAAAAAGCCACCGAAAAAGCCAGCGAAAAAAAAAAAAAAGCAAAAAAAAAGGGAAAAAAAAAAAAAACCAGGAAAAAAAGGACCAAAAAAACCGAAAAAAAAAAGCCGAAAAAAAAAAAAAAGGAGGGAAAAAGGGAGGAAAAAAAUCGAAAAA'

## HoglaFractal
#SS_Goal = '..(.((..(((((....(((((......))))))))))((((...((((.....))))))))(((..(((....)))))).(((...((((...((((......))))))))(((..(((.....))))))((.((....)))).((((....(((..(((......))))))((.((.....))))(((....))).(((((.....((.((......))))(((.....)))((....)).((((((......(((......)))((.....))...(((((((...))))))).......))))))......))))).....))))....)))...))..)...(.((.((((....((....))((....))((((((...)))))).)))))).)'
#PS_Goal = 'ACGUCCAACUUAUAAAAUAUAUGAAAAAGUGUAGUAAGCAGCAAAUUAAGAAAAUUAAGCUGGCGAAUUAGAAAUAACGCAGUCAAACAUCAAAGUGUGAAAAAAUACGAUGGCCAAUGGGAAAACUAGGCGCACAGAAAUGGCAGAGCAAAACUGAACUAGAAAAAUAGCAGCCACCGAAAAGGGGGGAGAAAUCCAGGAUUAAAAACGUAGGAAAAACUCGGCCGAAAAGGCGGGAAACCAGUGUAUAAAAAACUCGAAAAAGGGGGGAAAACCAAAGUGAUAUAAAGUAUUAUAAAAAAAGUAUAUAAAAAAGAUUCAAAAAGCUCAAAAGACAAAGGUUCAAAGGUGAUAUCAAAAGGGAAACCGCGAAAGCCUAUAUAAAGUGUAGAGAUACAGC'

## 16S
IUPAC_Goal = 'AAAUUGAAGAGUUUGAUCMUGGCUCAGAUUGAACGCUGGCGGCAKGCYUAACACAUGCAAGUCGARCGGNARCRNDDNNNNVYUYRBDNNNNDGVYGNYKAGYGGCGRACGGGUGAGUAAYRYNURGGRAHHURSCYDDWNGWGGGGGAYARCNNNBSGAAASBNNNRYUAAUACCGCRURVBNYCKNVRGRNBAAAGNDKGSGAHYKYHDRDSCWBNYRCBWHNRGAUDDRCCYRNRUSVGAUUAGSUWGWWGGYRRGGUAANRGCYYACCWWGSCDRCGAUCBSUARCKGKUYUGAGAGGAYGAYCMGYCACAYYGGRACUGAGACACGGYCCRRACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGSRCAAUGGGSGVAASCCUGAYSCAGCMAUGCCGCGUGDRUGAAGAAGGYYUKHKGRUUGUAAAGYHCUUUMRKYNDKGARGARRVGNNNNNNNYUAAUANNNNNNNNNNDKGACRUUAVHNRMAGAAKAAGSACCGGCUAACUYYGUGCCAGCAGCCGCGGUAAUACRRRGGGUSCRAGCGUUAAUCGGAWUDACUGGGCGUAAAGSGHRYGYAGGYGGYBNNDYAAGYBDRNUGUGAAAKCCCBGRGCUYAACYUVGGAAYDGCAKYBVRDACUGNNNNRCUWGAGUVBNDBAGRGRRDRGURGAAUUYCMBGUGUAGCRGUGAAAUGCGUAGAKAUVKGRAGGAAYAYCRRWGGCGAAGGCRRCYHYYUGGVHNNRBACUGACRCUSAKRYDCGAAAGCRUGGGKAGCAAACRGGAUUAGAUACCCYGGUAGUCCAYGCYSUAAACGMUGWCDAYUHGNNGNYBGDNNHHWHDDDNNBUBDBBNNYVNAGCWAACGYRHUAARUHSWCCGCCUGGGGAGUACGGYCGCAAGRYUAAAACUCAAAKGAAUUGACGGGGGCCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAWGCAACGCGAAGAACCUUACCWRSHCUUGACAUVBHNNGAABHNNBYAGAGAURNNNDDGUGCCUUCGGGARYNNDVABACAGGUGCUGCAUGGCUGUCGUCAGCUCGUGUYGUGARAUGUUGGGUUAAGUCCCSBMACGAGCGCAACCCYUDUCCYUDKUURCYAGCRVKHHDKBYGGGMACUYHARGGAKACUGCCRGUGAYAAACYGGAGGAAGGYGGGGAYGACGUCAAGUCAUCAUGGCCCUUAYGDSYWGGGCUACACACGUGCUACAAUGGYVNRUACARAGDGHDRCNAVVBNGCGANVKBRWGYNRAYCHYWNAAARYNBRUCKHAGUCCGGAUYGSAGUCUGCAACUCGACUSCRUGAAGUCGGAAUCGCUAGUAAUCGYRDAUCAGMAUGHYRCGGUGAAUACGUUCCCGGGCCUUGUACACACCGCCCGUCACACCAUGGGAGUKKRYUGYWMMAGAAGYRGNUAGYYUAACCBYHRGGRGRRCGNUYACCACKKWRKKRYYSAUGACUGGGGUGAAGUCGUAACAAGGUARCCSUAGGGGAACCUGSGGYUGGAUCA'
PS_Goal =    'AAAUUGAAGAGUUUGAUCAUGGCUCAGAUUGAACGCUGGCGGCAGGCCUAACACAUGCAAGUCGAACGGUAACAGGAAGAAGCUUGCUUCUUUGCUGACGAGUGGCGGACGGGUGAGUAAUGUCUGGGAAACUGCCUGAUGGAGGGGGAUAACUACUGGAAACGGUAGCUAAUACCGCAUAACGUCGCAAGACCAAAGAGGGGGACCUUCGGGCCUCUUGCCAUCGGAUGUGCCCAGAUGGGAUUAGCUAGUAGGUGGGGUAACGGCUCACCUAGGCGACGAUCCCUAGCUGGUCUGAGAGGAUGACCAGCCACACUGGAACUGAGACACGGUCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGCGCAAGCCUGAUGCAGCCAUGCCGCGUGUAUGAAGAAGGCCUUCGGGUUGUAAAGUACUUUCAGCGGGGAGGAAGGGAGUAAAGUUAAUACCUUUGCUCAUUGACGUUACCCGCAGAAGAAGCACCGGCUAACUCCGUGCCAGCAGCCGCGGUAAUACGGAGGGUGCAAGCGUUAAUCGGAAUUACUGGGCGUAAAGCGCACGCAGGCGGUUUGUUAAGUCAGAUGUGAAAUCCCCGGGCUCAACCUGGGAACUGCAUCUGAUACUGGCAAGCUUGAGUCUCGUAGAGGGGGGUAGAAUUCCAGGUGUAGCGGUGAAAUGCGUAGAGAUCUGGAGGAAUACCGGUGGCGAAGGCGGCCCCCUGGACGAAGACUGACGCUCAGGUGCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGUCGACUUGGAGGUUGUGCCCUUGAGGCGUGGCUUCCGGAGCUAACGCGUUAAGUCGACCGCCUGGGGAGUACGGCCGCAAGGUUAAAACUCAAAUGAAUUGACGGGGGCCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAUGCAACGCGAAGAACCUUACCUGGUCUUGACAUCCACGGAAGUUUUCAGAGAUGAGAAUGUGCCUUCGGGAACCGUGAGACAGGUGCUGCAUGGCUGUCGUCAGCUCGUGUUGUGAAAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCUUAUCCUUUGUUGCCAGCGGUCCGGCCGGGAACUCAAAGGAGACUGCCAGUGAUAAACUGGAGGAAGGUGGGGAUGACGUCAAGUCAUCAUGGCCCUUACGACCAGGGCUACACACGUGCUACAAUGGCGCAUACAAAGAGAAGCGACCUCGCGAGAGCAAGCGGACCUCAUAAAGUGCGUCGUAGUCCGGAUUGGAGUCUGCAACUCGACUCCAUGAAGUCGGAAUCGCUAGUAAUCGUGGAUCAGAAUGCCACGGUGAAUACGUUCCCGGGCCUUGUACACACCGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGGUAGCUUAACCUUCGGGAGGGCGCUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAGGUAACCGUAGGGGAACCUGCGGUUGGAUCA'
SS_Goal =    '........((((.........)))).((((.(((((..(((((((((....(((.(((..(((..((.((..(((....(((....))).....)))))..)))))......(((......(((((((..((...(((((((.(.((.....((((((....))))))......)).).....(((....)))....((((((..........)))))).)))))))..)).)))))))(((....(((..((((((((.......)))))))))))......)))..((((((((....))))...))))))).(((((............))))).((((....))))...)))))).).....(.(((...(((((....)))).))))).)).))))))..((((......((((....)))).....))))..((.(((((......(.((((((((.......)))))))).)........)))))....)).(((((......(((((.....((....)).......))))))))))..)))))))))..........(((.....(.((((...(((.(((((((.((((((((((......((((((.....))))))....))))))))..)))))))))..(((((((((...((((((((...((((((((...((........))......))))))))...).......((....)).)))))))..)))).))))..))))...))))....((((((...((...((((.........))))...))))))))..........((((((..((((((((((((.....))))))))))))...((....)).....)))))))))).(((......((((....))))....)))........(((((.(((((((.((..(((((..((((((((((......((........))..........(((((((..(...(((((((.................................))))).))).((.(((...((((((.(....(((((((((....)))...(((......)))...)))))).....((((.(((((((...((..((.......))))....))))))).....(((((.....)))))........)))).....).).)))...)).)))))....)))))))...)).)))))))).....((((((......(((..((...(((....)))...))....)))......))))))...........(((((((........)))))))..........))))).....(((((((.........)))))))......))...)))))))))).)).......((.(.((((.(((..((((((((((((....((((((.((((..((....)).))))))))))...))))))))))))..))).))))..).)).........(((((((((....)))))))))......'
LS_Goal =    'ooooooooooooooxoxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooxoooooooooooooooooooooxxxooooooooooooooooxxxoooooooooooooooooooooooooooooooooooooooooooxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooxxoooooooooooooooooooooooooooooooooooooooooooooooooxxxoxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooxoooooooxooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooxooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooxooooooooooooooooooooooooxooooo'

# ## Ribosome
# Name = '23S Ribosome'
#SS_Goal = '((((((((......((((((((((......((..(((((((((((((......((((((........))).....((((((...(((.......))).......))))))...)))....(((....)))(((((.(....).))))).(((((((((.........))))))))).))...((((((...................))))).).........((....))...(((((.....((.....))....)))))...(((..((((......(((((((((.(((.(((...(((((......)))))........(((.......)))...)))...))).)))))))))...))))........((((((((.........))))))))......(((((......)))))..)))......)).))))))).))...............((....))....)).........((((.....))))...................)))))))))).......((((..(((((......)))))..))))..................((((((....(((((((((((((..(((...((.....))...)))...((....))..((((.....)))).....)))))))))))))..((.....((((((.....((((((((((.((((...((((((......))))))...).)))...(((.(((((........))))))))..).)))))))))...(((.....)))......))))))........))..((((((....(((((....))))).((((((((..((((((((((.....(((...(((.((((...((.((.........))..))...)))).)))..)).).....)))))).)))..)))))))).)...(((((((((........)))))))))....(((......)))...((((.(((...(((......(.((((((...........((..(((((..(((.......(((((.(((..(((.........)))..))).....(..(((......)))).)))))...)))..))))).))...................))))))))))...)))))))((((((((......))))))))....))))))..(((((...(((......((((((((....))))))))...)))..)))))........)))))).......((.....((((((.......))))))((((....((((..((..(((((((...((.....)).))))))......(((.(((.(.(((...(((....)))...)))..))))..(((((........)))))..(((((((((((((...((((....((((..(((..((((((((((((.......).))))))((..((((....(((((((((((.((.....))))))))))..)))....))))...))(..(((((....)))))...))))))...)))...)))).........))))...))....))))))))))).))).))).....((......)).)))).((((.....))))..))))..((((....((((((((.((..(............(((((...............)))))((((((.....(((...((((.....))))...)))...))))))............(((((((((...((.........))...(((((((.....(((....))).......)))))))..((((.(((..(((((((..(((........(((((..((....))...)))))........))))))))..)))))(((((.........)))))....................(((((.......)))))..........))))...)).)))))))....))).)))))))).))))))...........(((((........)))))..((((((((.(((.((......((((.((((((..(((((.(((.(((((.((((((((((...((...............((...((......(.((((((....)))))).)...)).............))......))...))))))))))...(((.((((((.....)))))))))....))))).)))..)))))..(((.......)))((((((...........))))))..((...(((((((...((((((.......)))))).....((......))....)))))))...((((..((((....))))..)))).(((....))).))..........(((((((.((........))))))))).............))))..))))))......((((..(.((((((...((.......))...))))))...).)).).).....((.((.((((((..(((((((((......))))))..))).(((((.....))))).....)))))..)...))..))....(..((((....))).)..)....))..)))))))))))....(((((((...((((..(((((((...............))))))).(((((...((((...(((((((((((....))))))..)))))...)))).)))))...(((....((((.............))))....))).)))).......)))))))(.(((((.....))))).....((..(((((.......)))))....((((((((..((....(((((....)))))...))...))))).))).....))....))))))))).'
#PS_Goal = 'GGUUAAGCGACUAAGCGUACACGGUGGAUGCCCUGGCAGUCAGAGGCGAUGAAGGACGUGCUAAUCUGCGAUAAGCGUCGGUAAGGUGAUAUGAACCGUUAUAACCGGCGAUUUCCGAAUGGGGAAACCCAGUGUGUUUCGACACACUAUCAUUAACUGAAUCCAUAGGUUAAUGAGGCGAACCGGGGGAACUGAAACAUCUAAGUACCCCGAGGAAAAGAAAUCAACCGAGAUUCCCCCAGUAGCGGCGAGCGAACGGGGAGCAGCCCAGAGCCUGAAUCAGUGUGUGUGUUAGUGGAAGCGUCUGGAAAGGCGCGCGAUACAGGGUGACAGCCCCGUACACAAAAAUGCACAUGCUGUGAGCUCGAUGAGUAGGGCGGGACACGUGGUAUCCUGUCUGAAUAUGGGGGGACCAUCCUCCAAGGCUAAAUACUCCUGACUGACCGAUAGUGAACCAGUACCGUGAGGGAAAGGCGAAAAGAACCCCGGCGAGGGGAGUGAAAAAGAACCUGAAACCGUGUACGUACAAGCAGUGGGAGCACGCUUAGGCGUGUGACUGCGUACCUUUUGUAUAAUGGGUCAGCGACUUAUAUUCUGUAGCAAGGUUAACCGAAUAGGGGAGCCGAAGGGAAACCGAGUCUUAACUGGGCGUUAAGUUGCAGGGUAUAGACCCGAAACCCGGUGAUCUAGCCAUGGGCAGGUUGAAGGUUGGGUAACACUAACUGGAGGACCGAACCGACUAAUGUUGAAAAAUUAGCGGAUGACUUGUGGCUGGGGGUGAAAGGCCAAUCAAACCGGGAGAUAGCUGGUUCUCCCCGAAAGCUAUUUAGGUAGCGCCUCGUGAAUUCAUCUCCGGGGGUAGAGCACUGUUUCGGCAAGGGGGUCAUCCCGACUUACCAACCCGAUGCAAACUGCGAAUACCGGAGAAUGUUAUCACGGGAGACACACGGCGGGUGCUAACGUCCGUCGUGAAGAGGGAAACAACCCAGACCGCCAGCUAAGGUCCCAAAGUCAUGGUUAAGUGGGAAACGAUGUGGGAAGGCCCAGACAGCCAGGAUGUUGGCUUAGAAGCAGCCAUCAUUUAAAGAAAGCGUAAUAGCUCACUGGUCGAGUCGGCCUGCGCGGAAGAUGUAACGGGGCUAAACCAUGCACCGAAGCUGCGGCAGCGACGCUUAUGCGUUGUUGGGUAGGGGAGCGUUCUGUAAGCCUGCGAAGGUGUGCUGUGAGGCAUGCUGGAGGUAUCAGAAGUGCGAAUGCUGACAUAAGUAACGAUAAAGCGGGUGAAAAGCCCGCUCGCCGGAAGACCAAGGGUUCCUGUCCAACGUUAAUCGGGGCAGGGUGAGUCGACCCCUAAGGCGAGGCCGAAAGGCGUAGUCGAUGGGAAACAGGUUAAUAUUCCUGUACUUGGUGUUACUGCGAAGGGGGGACGGAGAAGGCUAUGUUGGCCGGGCGACGGUUGUCCCGGUUUAAGCGUGUAGGCUGGUUUUCCAGGCAAAUCCGGAAAAUCAAGGCUGAGGCGUGAUGACGAGGCACUACGGUGCUGAAGCAACAAAUGCCCUGCUUCCAGGAAAAGCCUCUAAGCAUCAGGUAACAUCAAAUCGUACCCCAAACCGACACAGGUGGUCAGGUAGAGAAUACCAAGGCGCUUGAGAGAACUCGGGUGAAGGAACUAGGCAAAAUGGUGCCGUAACUUCGGGAGAAGGCACGCUGAUAUGUAGGUGAGGUCCCUCGCGGAUGGAGCUGAAAUCAGUCGAAGAUACCAGCUGGCUGCAACUGUUUAUUAAAAACACAGCACUGUGCAAACACGAAAGUGGACGUAUACGGUGUGACGCCUGCCCGGUGCCGGAAGGUUAAUUGAUGGGGUUAGCGCAAGCGAAGCUCUUGAUCGAAGCCCCGGUAAACGGCGGCCGUAACUAUAACGGUCCUAAGGUAGCGAAAUUCCUUGUCGGGUAAGUUCCGACCUGCACGAAUGGCGUAAUGAUGGCCAGGCUGUCUCCACCCGAGACUCAGUGAAAUUGAACUCGCUGUGAAGAUGCAGUGUACCCGCGGCAAGACGGAAAGACCCCGUGAACCUUUACUAUAGCUUGACACUGAACAUUGAGCCUUGAUGUGUAGGAUAGGUGGGAGGCUUUGAAGUGUGGACGCCAGUCUGCAUGGAGCCGACCUUGAAAUACCACCCUUUAAUGUUUGAUGUUCUAACGUUGACCCGUAAUCCGGGUUGCGGACAGUGUCUGGUGGGUAGUUUGACUGGGGCGGUCUCCUCCUAAAGAGUAACGGAGGAGCACGAAGGUUGGCUAAUCCUGGUCGGACAUCAGGAGGUUAGUGCAAUGGCAUAAGCCAGCUUGACUGCGAGCGUGACGGCGCGAGCAGGUGCGAAAGCAGGUCAUAGUGAUCCGGUGGUUCUGAAUGGAAGGGCCAUCGCUCAACGGAUAAAAGGUACUCCGGGGAuAACAGGCUGAUACCGCCCAAGAGUUCAUAUCGACGGCGGUGUUUGGCACCUCGAUGUCGGCUCAUCACAUCCUGGGGCUGAAGUAGGUCCCAAGGGUAUGGCuGUUCGCCAUUUAAAGUGGUACGCGAGCUGGGUUUAGAACGUCGUGAGACAGUUCGGUCCCUAUCUGCCGUGGGCGCUGGAGAACUGAGGGGGGCUGCUCCUAGUACGAGAGGACCGGAGUGGACGCAUCACUGGUGUUCGGGUUGUCAUGCCAAUGGCACUGCCCGGUAGCUAAAUGCGGAAGAGAUAAGUGCUGAAAGCAUCUAAGCACGAAACUUGCCCCGAGAUGAGUUCUCCCUGACCCUUUAAGGGUCCUGAAGGAACGUUGAAGACGACGACGUUGAUAGGCCGGGUGUGUAAGCGCAGCGAUGCGUUGAGCUAACCGGUACUAAUGAACCGUGAGGCUUAACCU'
#LS_Goal = 'ooooxxooxxoxxxooxxooooxooxxxxxoxxoxxxxooooooxoxxxoxxxxxooxxxxxxxxxxxxooxxxxooxxxoxxxxooxxxxoxoooxxoxooxxoxxxooxxooxxxxxxooxxxxxxooooooooooooxoooooooxoooooooooxxxxoxxxxoooooooooxxooxxxxooxoxxxxxxxxxxxoxxxxxxxoxooxxxxxxoxxoxxoxxxxxxoxxxxoxxoxxxxxxoxxxxxoxxxxxoxxoxooxooooooooooooxxoooooooooooooxxoooxxxooooxxxxxxoxooooxxxooxxxoooxxxoxxxoooxxxoooooxxoooooooooooooxoooooooooxxxxooooooooxxxxoxoxxooooooooxxxooooxxxxxxxxxxxxxxooxoooxoxxxxxoooooooxxxxxxxxxxoxoxxxxxxxxxxxxxxxxxxxxoxxxxxxxxooooxxxoxxxoooxxxxxxxoxxxoxxxxxxxoxooooxxooxxoxxoxxxxxxxxooooooooooooooxxxxxxxxxxxxooxxxoxxxoxxxoxxxoxxxxxxoooooooxxxxoxxoxoxxxooxooxxooxxxoxoxoxoxxxxxxoxxoxoxxxxxxxoxoxoooxoxxxxoooooooxxxxxxoxxxxxooxxxxxxxxooxxxooooxxooooxxooooooxxoxoxooooooxxooxooxxxxooxooxoxxxxxxxxooxxoxoxooxxoxoooxxxooxxxxoxoxxoxooxooxoxxxxxooxxxxxxoxoxxxxxxxxoxoxxxxoxxoxooxxxoxxoxxxxooooxxoooxoxooxxoxxxxxoxxxxxxxooooooooxooxoooooooooooooxoooxooooooooxxxxxxooxxxxxoxxooxooxoxxoxooooxxxxxxxxxxoooxxxxxxxxxxxxxxoooxxxxxxxxxooxxoxxoxxoxxoxoxxoooxxxxxoxxxoxxoxoooooxxxxxxxxooxxxxxoxxoooxoooxoooxxxooooxxxxxxxoxxxxxoxooxxxxxxxoxxxxxxxxoxxoxxxxoxoxxxooxxxooooxoxoooxoooxxxxxxxxxxxxoxoxxxxxxxxxxoooooooxxxxxoooxoxoooxxooooooooooooooxxooxxxxoxoxxxxxooxoxxxxooxxxoxxxxoooooooxoxxoooooooxxxxxooxxxoxooxxxxxxxxxoxxxoxxxxxxxoxxooxxxoooooxxoxxxxoooooxxxxxxxxxxoxoxxxxoxxxxoooxxoxxxoxxxxxxxxoooxxxxoxxxxooxoxxxxxoooxxxoxxxxxxxxoxxxoooxxxxxoxxxxoooxxxxxxxxoooxxxxxoooooooooxxoxxxxxooxxxxxoxoxoxxoxxooxoooxxoooxxoxxxxoxooooxxoooxxooooxxxxooooooooooxooxoxxxxxoxooooooooooooxxxxooooxoooooxooooooooooooooooxxoooxooxxxoxxooxoxoxxoxxxxxxxooxxxoxoxooxxxoooooooooxxooxxxxxxxxxxxxxxxxxoxxxoxoxxoxxxxxxxxxxxoxxxxxxxxoxoxxxoxooooxxooxxxxxxxxoxxxxxxoxxxoooxxxxxxxxoxxxxxxxxoooxoxxoooxoxxxoxxoxxooooooooxooooxxoxxoxxxoooxxooxxxoooxxoxxoooooooxxxxxxxxxxoxxxxxxxxxxxxxxoxxxxxxxoxxxoxxxxoxxxxxxxxxoxxxxxxooxxxoxxxooxooooxoxoooxxxxxxxxooooxoooooxoooooooxooooxxxxxxxxoooxoooooxxoxxooooooxxxxoxxxxoooooxxxxxxxxxxxxxxxxxxxxxoxxoxxxxxxxoxxoxooxxxxxxxoxxooxxxxxxooooooooxxxxxxxooxxooooxxoxoxoxxxxxxoxxxxxxoxxxxxxxxxxxxoxxxoxxxoxxooxooxxooooxxoxxxoxxxoxxxxxoxxxooxooxxxooxoxxoooooooooxoxoooxoxooxoxxxxoxoooxoxoooooxxxoxoooooxxooxxoooooxoxxxooxooooxxoxoxoooooxooxoooxoxoooooooooxxxxxoooxooxxooxxxxoxxooxooxxxoxoxooxxxooxxooxxxxxoooxxxoooxooooxxxxxoxxxooxxxxxxxxxxooxxxoxxxxxooooxxxoooxoxxooooooxoxoooxxxxxxxxxxxxxxxxoxxooooxxxxxxoxxxxxxoooxxxxoooxxxxxxoxxoxxxxxxoxxxxxxxxxoxxxxoxooooxoooxoxxxxxxooxooooxoxoxxooxxxxxxxxxxxxxoxxoxxxxxxxxxxxxxxoxoxxxxxxxxxoxooxxoxoxxxxxxxxxoxxxoxxxxxoxxxoxxoxxoxxxxxxxxxxxxxxxooxxxxxxooxxooxxxxxxxxxxxoxoxooxxoxxxxxxxxxxxxxooxxxxxoxxxoooxxxxxxxoxxxxxxoxoxxxxxxoxooxxxooooxxoxxxxxoxxxxxooxxxxooooxxoooooooxxxxxxxoxxxxxxxoooooooxooooxxxxxxxxxxxxxxxxxxxooxxxxoxooxxxxoxxxxxxxxxxxxxxooooxoxoooxxxxooxxxxxxxxxxxxxxxxxooxxxxoooxooooxxxxxxxxooxxxxxxoooooooooxooooooxoxxooxxxxxoooxxxxxxooxxxooxxxxxxoooooxxxxxoxoooooxoxxoooooxxxxxxoxooooxxxxxxxxoxooxxoxxooxxoooooo'
# #23S 05/08/2019
# LS_Goal = 'ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooxxxoooooooooooooooooooooxxxooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooxoxxxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxoooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooxoooooooxoooooooooooooooooooooooooooooooooooooooooxxoxxxooooooooooooooooooooooooooooxoooooooooooooooooooooooooxxxoxoooooooooooooooooxxxxoooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo'
# IUPAC_Goal = 'RRUYARGYRRHBAAGBGYAYRHGGYRRAUGCCYDGGCRRWVASAGGCGAWRAARGRCGURNDWDBBKRCGAWAASBBNNGRBVAGBYRRBADNRDVCNNWNNNNNCNNVSAUNYYYGAAURGGRVAAYCCRVYNNNNNUHRNNNNRBYWWYDHNHNVBNRAUHCAUMRBNDNDHRRRGSDAASSNRGDRAASUGAAACAUCUHAGUABYYNBAGGARMRGAAAUCAAYHGAKAUUYCSNHAGUAGYGGCGARCGAAMVBGRANNAGYCHNGARCCUGAAUCAGYRKRUGUGUUARNDRAABSRUYUGGAAARKYVMRCSRDASHRRGUGABADYCYBGUANNYAAAAAUGCACAURCUGUGAGCUCRMHRARUARRDCGRVRCACGWGDHAYBYUGWYUGAANAWRGGGGGMCCAUCCUCYAAGRCUAAAUACUMSUBWYYGACCGAUAGYGAACHAGUACYGURARGVAARGKBRAAAAGAACCSCKGHDAGGGSAGUGAAAHAGAWMCURAAACYBBRURCVUACAAGCWGURGRAGYVNNNUUAGNBNKGYGACUGCGUACCUUUUGUAUMAUSGGUCAGCGASUURYWYDYHGURGCRAGSUUAABCRHVUAGSGDAGSCGNARVRAAABCGAGUYYKAAHHRRGCRHUAAGUYKCDRBVWRYASACCSRAMMCSNRRYGAUCUABYYAUGRBCAKGDWGRRKGYNRRGUAAHAYYDRCUGRAGGDCCGAMCYSACKNHYGUKRMAARRBBMGSGGAUGAVHUGUGRMUVGGRGUGAAAGRCYAAWCAARYYNGGWGAUAKCUGGUUCUCCYCGAAAKCUAUUKAGGUAGMGCSUHNNRNDHWNRYYNNNSGRGGUAGAGCWCUGUUWNGRYHAKRGGKYYWBMCCGVMYURBSRANYCNWKGCAAACUVCRAAUACBNNNRRRYDHNDDYNYRGSAGWCABWCDRCGGKUGMUAASSWYCGUNGUSRARAGGRWRAVRRYCCAKAYCGHCRGMUMRSRNCYCVARRUYNHDRYUMAGUGGKAAACGAWGUGGGAARGCHYAVACARCYAGGABSUUKGCYUAGAMGCAGCCAHCMUUWAAAGAAAGCSUAAUAGCUCACURGWCRAGUYRKYCYGCGCGGAAGAUDUAACGGGGYWAARYHDNRYRCCRAAGCYRCGGCAGCGACRCUUAUGCGUUGUUGGGUAGRGGAGCGUUSKGUAMGBSDDHGAAGRKNNNYYGDRARRBNKRYUGGASVUAUCMSAAGUGCGAAUGCUGACRURAGUARCGAYAADRBRDGUGAAAWVCHYVYHCGCCGDAARHCYAAGGDUUYCWGYBCAAMGUYAAUCKRVGCWGRGUDAGYCGRYHCCUAAKRYRAGGCHGWRRDGCGUARHYRAUGGRWADYNGGUUAAUAKUCCNRHRCUUGGUGUUACUGCGAAGGGGGGACGGAGAAGGCUAUGUUGGCCGGGCGACGGUUGUCCCGGUUUAAGCGUGUAGGCUGGUUUUCCAGGCAAAUCCGGAAAAUCAAGGCUGAGGCGUGAUGACGAGGCACUACGGUGCUGAAGCAACAAAUGCCCUGCUUCCAGGAAAAGCCUCUAAGCAUCAGGUAACAUCAARYCGUACYNNAAACSRACACASGURGDYRGGWHGARWAKWCYMAGGCGCUUGAGAKAMCYYDGSUGAAGGAACUMGGCAAAWURRHRCCGUAACUUMGGRAGAAGGYDYGCYVNYAUGUAGGUGARGUCCCUCGCGGAUGGAGCUGAARNBRGYBRMAGHDAHSMGVYSGCUGSRACUGUUUAHYAAAAACAYRSVACWSUGCDAAVDCGNAAGHBRRMGUAUASKGUSUGAYRCCUGCCCGGUGCYKGAAGGUUAADYRADRRDGUHADMBHMRKHRAAGCWYYDRAHHGAAGCCCCRGUAAACGGCGGCCGUAACUAUAACGGUCCYRWKGUAGYKAMRUWCCUUGUCGGGYAAGUWYSGACCUGCACGAAUGGYRUAAYSAYGGCSRBRCUGUCUCCASCHGRGRSUCAGYRAARWYGAANUYGCHGHKAAGRURCDGYRUWYCCRYGGCWAGACGGAAAGACCCCGUGMACCUUUACURYARCUUDRYAYKGAHCHYYRRNHHBDNHYGUGYAGRAUAGVUGGKAGVCWDWGAARNNNDDRCGCYAGYHNBNNUGGAGBCRDHSKUGAAAUACCABYCUKBNNNNBYYKDKGYUCUMACBHNRNNBHVKNAHHBKRNNHDVRRACMRUGYHWGGYRGGYAGUUUGACUGGGGCGGUCUCCUCCYAAARNGUAACGGAGGAGYRCDAARRUDNVCUMAKMVYGGUYGGAHAUCRBKMRBWKWGURYAAWGGYANAAGBNHGYUUVACUGYGAGMVNBAYRVBKCRAGCAGRURCGAAAGYAGGUCWUAGUGAUCCGGURGUYCUKHAUGGAARGGSCAUCGCUCAACGGAUAAAAGGUACKCYGGGGAUAACAGGCURAUWCCVCCCAAGAGYUCAYAUCGACGGBGGWGUUUGGCACCUCGAUGUCGGCUCAUCDCAUCCUGGRGCUGHAGYNGGUCCCAARGGUAUGGCUGUUCGCCAUUUAAAGHGGUACGYGASCUGGGUUYARAACGUCGUGAGACAGUUYGGUCCCUAUCURYCRUGGRHGHWDGADDWYUGADDRRRKYUGMYYYUAGUASSAGAGGACCRRRKUGRACGHRYYDCUGGUGUWYVGGUUGUBHYGCCARDSGCAYHGCCBGGUAGCUAHRUDCGGHMDNGAUAASYGCUGAAMGCAUMUAAGCRBRARRCBHVYYHHRAGAUDARWHHKCHSKRRVNVHDHRDBNBYHYDDAAGRDNYGUBVNAGACBABVASGUWRAUAGGYNVSRWGUGDARKYDHDRNDWKDHRUKNAGCKRASBNRUACUAAUBRVYCGWGMGRCUURAYYH'


# Substitute_PS_Long = 'GCUGCGAAAGCAGC'
# Substitute_SS_Long = '(((((....)))))'
# Substitute_LS_Long = 'oooooooooooooo'
# Substitute_IG_Long = 'SSWSSYNNNSSWSS' #strong opening
# #Substitute_IG_Long = 'YRYRYYYYYRYR' #this would match generic versions of the GCUGCGAAA... hp above


#This the substitute HP length (
Substitute_PS_Long = 'GCAUGCGAAAGCAUGC'
Substitute_SS_Long = '((((((....))))))'
Substitute_LS_Long = 'oooooooooooooooo'
Substitute_IG_Long = 'NNNNNNNNNNNNNNNN'
SubsHP = {1:Substitute_PS_Long, 2: Substitute_SS_Long, 3: Substitute_LS_Long, 4: Substitute_IG_Long}

#This is how HPs -> bulges are replaced
GenSub = {1:'A',2:'.',3:'x',4:'A'}
