

# Shooting Star
#Name = 'ShootingStar'
#SS_Goal = '(((((((((((((((((...(.(..((.(((.(((.((....).))).)))).).)..))..))))))).(((((..(.(..((.(((.(((((.(((.((((.((....).)))).))))).))).)))).).)..))..)(....)..))))(((((((((...))))).(((((...)))))(.(....).).)))).)))).((((.((((...(((((((...))))))).(((((...)))))))))(((((((...))))))).(((((...)))))))))((((..(....)(..(..(..(.(.(((.((((.((....).)))).)))).)..)..).)..))))).)))))).'
#PS_Goal = 'UAUAUGCCCCCUAUAUCGAAGAUUGACGCUGACCGACCGAAAGCGCGCGCAGGGAUUGACGAGAUAUAGACCCAGUGGAUUGCCGUAGACCAGCGCCGACCAGACCGAAAGCGCUGCGCGGGACUGCGCUAGGAGUGACUGCCGAAAGAAUGGGGGCCGUAUGAAACAUACACUAUGAAACAUAGCGGGAAACGGAGGCCAGGGGAUCCCAGGACAAGUAUAUACAAAGUAUAUAACAUAGAAACUAUGGUCCGUAUAUAAAAUAUAUACAAUACGAAACGUAUGGGAGCGGAACGAAAGGUGGGGCUGCACGGAGACCAGACCGAAAGCGCUGCGCUCGGGGGUGGACUGCCCGCACAUAUAA'

## Teslagon
#SS_Goal = '......((.......((.((.......((.((...............)).........((...............)).)).......)).((.......((...............)).......)).((.......((.((...............)).........((...............)).)).......)).((.......((...............)).......)).((.......((.((...............)).........((...............)).)).......)).((.......((............((...............)).)).......)).)).......))......'
#PS_Goal = 'AAAAAAGAGAAAAAGCCAGCGAAAAAAGGAGGGAAAAAAAAAAAAAACCAAAAAAAAAGCGAAAAAAAAAAAAAAGCACCGAAAAAAGCAGCGAAAAAAGGGAAAAAAAAAAAAAACCGAAAAAAGCAGGGAAAAAAGCAGGGAAAAAAAAAAAAAACCAAAAAAAAAGCGAAAAAAAAAAAAAAGCAGCGAAAAAACCAGGAAAAAAGCCGAAAAAAAAAAAAAAGGAAAAAAGCCACCGAAAAAGCCAGCGAAAAAAAAAAAAAAGCAAAAAAAAAGGGAAAAAAAAAAAAAACCAGGAAAAAAAGGACCAAAAAAACCGAAAAAAAAAAGCCGAAAAAAAAAAAAAAGGAGGGAAAAAGGGAGGAAAAAAAUCGAAAAA'

## HoglaFractal
#SS_Goal = '..(.((..(((((....(((((......))))))))))((((...((((.....))))))))(((..(((....)))))).(((...((((...((((......))))))))(((..(((.....))))))((.((....)))).((((....(((..(((......))))))((.((.....))))(((....))).(((((.....((.((......))))(((.....)))((....)).((((((......(((......)))((.....))...(((((((...))))))).......))))))......))))).....))))....)))...))..)...(.((.((((....((....))((....))((((((...)))))).)))))).)'
#PS_Goal = 'ACGUCCAACUUAUAAAAUAUAUGAAAAAGUGUAGUAAGCAGCAAAUUAAGAAAAUUAAGCUGGCGAAUUAGAAAUAACGCAGUCAAACAUCAAAGUGUGAAAAAAUACGAUGGCCAAUGGGAAAACUAGGCGCACAGAAAUGGCAGAGCAAAACUGAACUAGAAAAAUAGCAGCCACCGAAAAGGGGGGAGAAAUCCAGGAUUAAAAACGUAGGAAAAACUCGGCCGAAAAGGCGGGAAACCAGUGUAUAAAAAACUCGAAAAAGGGGGGAAAACCAAAGUGAUAUAAAGUAUUAUAAAAAAAGUAUAUAAAAAAGAUUCAAAAAGCUCAAAAGACAAAGGUUCAAAGGUGAUAUCAAAAGGGAAACCGCGAAAGCCUAUAUAAAGUGUAGAGAUACAGC'

## 16S
#PS_Goal =    'AAAUUGAAGAGUUUGAUCAUGGCUCAGAUUGAACGCUGGCGGCAGGCCUAACACAUGCAAGUCGAACGGUAACAGGAAGAAGCUUGCUUCUUUGCUGACGAGUGGCGGACGGGUGAGUAAUGUCUGGGAAACUGCCUGAUGGAGGGGGAUAACUACUGGAAACGGUAGCUAAUACCGCAUAACGUCGCAAGACCAAAGAGGGGGACCUUCGGGCCUCUUGCCAUCGGAUGUGCCCAGAUGGGAUUAGCUAGUAGGUGGGGUAACGGCUCACCUAGGCGACGAUCCCUAGCUGGUCUGAGAGGAUGACCAGCCACACUGGAACUGAGACACGGUCCAGACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGCACAAUGGGCGCAAGCCUGAUGCAGCCAUGCCGCGUGUAUGAAGAAGGCCUUCGGGUUGUAAAGUACUUUCAGCGGGGAGGAAGGGAGUAAAGUUAAUACCUUUGCUCAUUGACGUUACCCGCAGAAGAAGCACCGGCUAACUCCGUGCCAGCAGCCGCGGUAAUACGGAGGGUGCAAGCGUUAAUCGGAAUUACUGGGCGUAAAGCGCACGCAGGCGGUUUGUUAAGUCAGAUGUGAAAUCCCCGGGCUCAACCUGGGAACUGCAUCUGAUACUGGCAAGCUUGAGUCUCGUAGAGGGGGGUAGAAUUCCAGGUGUAGCGGUGAAAUGCGUAGAGAUCUGGAGGAAUACCGGUGGCGAAGGCGGCCCCCUGGACGAAGACUGACGCUCAGGUGCGAAAGCGUGGGGAGCAAACAGGAUUAGAUACCCUGGUAGUCCACGCCGUAAACGAUGUCGACUUGGAGGUUGUGCCCUUGAGGCGUGGCUUCCGGAGCUAACGCGUUAAGUCGACCGCCUGGGGAGUACGGCCGCAAGGUUAAAACUCAAAUGAAUUGACGGGGGCCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAUGCAACGCGAAGAACCUUACCUGGUCUUGACAUCCACGGAAGUUUUCAGAGAUGAGAAUGUGCCUUCGGGAACCGUGAGACAGGUGCUGCAUGGCUGUCGUCAGCUCGUGUUGUGAAAUGUUGGGUUAAGUCCCGCAACGAGCGCAACCCUUAUCCUUUGUUGCCAGCGGUCCGGCCGGGAACUCAAAGGAGACUGCCAGUGAUAAACUGGAGGAAGGUGGGGAUGACGUCAAGUCAUCAUGGCCCUUACGACCAGGGCUACACACGUGCUACAAUGGCGCAUACAAAGAGAAGCGACCUCGCGAGAGCAAGCGGACCUCAUAAAGUGCGUCGUAGUCCGGAUUGGAGUCUGCAACUCGACUCCAUGAAGUCGGAAUCGCUAGUAAUCGUGGAUCAGAAUGCCACGGUGAAUACGUUCCCGGGCCUUGUACACACCGCCCGUCACACCAUGGGAGUGGGUUGCAAAAGAAGUAGGUAGCUUAACCUUCGGGAGGGCGCUUACCACUUUGUGAUUCAUGACUGGGGUGAAGUCGUAACAAGGUAACCGUAGGGGAACCUGCGGUUGGAUCA'
#SS_Goal =    '........((((.........)))).((((.(((((..(((((((((....(((.(((..(((..((.((..(((....(((....))).....)))))..)))))......(((......(((((((..((...(((((((.(.((.....((((((....))))))......)).).....(((....)))....((((((..........)))))).)))))))..)).)))))))(((....(((..((((((((.......)))))))))))......)))..((((((((....))))...))))))).(((((............))))).((((....))))...)))))).).....(.(((...(((((....)))).))))).)).))))))..((((......((((....)))).....))))..((.(((((......(.((((((((.......)))))))).)........)))))....)).(((((......(((((.....((....)).......))))))))))..)))))))))..........(((.....(.((((...(((.(((((((.((((((((((......((((((.....))))))....))))))))..)))))))))..(((((((((...((((((((...((((((((...((........))......))))))))...).......((....)).)))))))..)))).))))..))))...))))....((((((...((...((((.........))))...))))))))..........((((((..((((((((((((.....))))))))))))...((....)).....)))))))))).(((......((((....))))....)))........(((((.(((((((.((..(((((..((((((((((......((........))..........(((((((..(...(((((((.................................))))).))).((.(((...((((((.(....(((((((((....)))...(((......)))...)))))).....((((.(((((((...((..((.......))))....))))))).....(((((.....)))))........)))).....).).)))...)).)))))....)))))))...)).)))))))).....((((((......(((..((...(((....)))...))....)))......))))))...........(((((((........)))))))..........))))).....(((((((.........)))))))......))...)))))))))).)).......((.(.((((.(((..((((((((((((....((((((.((((..((....)).))))))))))...))))))))))))..))).))))..).)).........(((((((((....)))))))))......'
#LS_Goal =    'ooooooooooooooxoxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooxoooooooooooooooooooooxxxooooooooooooooooxxxoooooooooooooooooooooooooooooooooooooooooooxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooxxoooooooooooooooooooooooooooooooooooooooooooooooooxxxoxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooxoooooooxooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooxooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooxooooooooooooooooooooooooxooooo'
#IUPAC_Goal = 'AAAUUGAAGAGUUUGAUCMUGGCUCAGAUUGAACGCUGGCGGCAKGCYUAACACAUGCAAGUCGARCGGNARCRNDDNNNNVYUYRBDNNNNDGVYGNYKAGYGGCGRACGGGUGAGUAAYRYNURGGRAHHURSCYDDWNGWGGGGGAYARCNNNBSGAAASBNNNRYUAAUACCGCRURVBNYCKNVRGRNBAAAGNDKGSGAHYKYHDRDSCWBNYRCBWHNRGAUDDRCCYRNRUSVGAUUAGSUWGWWGGYRRGGUAANRGCYYACCWWGSCDRCGAUCBSUARCKGKUYUGAGAGGAYGAYCMGYCACAYYGGRACUGAGACACGGYCCRRACUCCUACGGGAGGCAGCAGUGGGGAAUAUUGSRCAAUGGGSGVAASCCUGAYSCAGCMAUGCCGCGUGDRUGAAGAAGGYYUKHKGRUUGUAAAGYHCUUUMRKYNDKGARGARRVGNNNNNNNYUAAUANNNNNNNNNNDKGACRUUAVHNRMAGAAKAAGSACCGGCUAACUYYGUGCCAGCAGCCGCGGUAAUACRRRGGGUSCRAGCGUUAAUCGGAWUDACUGGGCGUAAAGSGHRYGYAGGYGGYBNNDYAAGYBDRNUGUGAAAKCCCBGRGCUYAACYUVGGAAYDGCAKYBVRDACUGNNNNRCUWGAGUVBNDBAGRGRRDRGURGAAUUYCMBGUGUAGCRGUGAAAUGCGUAGAKAUVKGRAGGAAYAYCRRWGGCGAAGGCRRCYHYYUGGVHNNRBACUGACRCUSAKRYDCGAAAGCRUGGGKAGCAAACRGGAUUAGAUACCCYGGUAGUCCAYGCYSUAAACGMUGWCDAYUHGNNGNYBGDNNHHWHDDDNNBUBDBBNNYVNAGCWAACGYRHUAARUHSWCCGCCUGGGGAGUACGGYCGCAAGRYUAAAACUCAAAKGAAUUGACGGGGGCCCGCACAAGCGGUGGAGCAUGUGGUUUAAUUCGAWGCAACGCGAAGAACCUUACCWRSHCUUGACAUVBHNNGAABHNNBYAGAGAURNNNDDGUGCCUUCGGGARYNNDVABACAGGUGCUGCAUGGCUGUCGUCAGCUCGUGUYGUGARAUGUUGGGUUAAGUCCCSBMACGAGCGCAACCCYUDUCCYUDKUURCYAGCRVKHHDKBYGGGMACUYHARGGAKACUGCCRGUGAYAAACYGGAGGAAGGYGGGGAYGACGUCAAGUCAUCAUGGCCCUUAYGDSYWGGGCUACACACGUGCUACAAUGGYVNRUACARAGDGHDRCNAVVBNGCGANVKBRWGYNRAYCHYWNAAARYNBRUCKHAGUCCGGAUYGSAGUCUGCAACUCGACUSCRUGAAGUCGGAAUCGCUAGUAAUCGYRDAUCAGMAUGHYRCGGUGAAUACGUUCCCGGGCCUUGUACACACCGCCCGUCACACCAUGGGAGUKKRYUGYWMMAGAAGYRGNUAGYYUAACCBYHRGGRGRRCGNUYACCACKKWRKKRYYSAUGACUGGGGUGAAGUCGUAACAAGGUARCCSUAGGGGAACCUGSGGYUGGAUCA'

# ## Ribosome
# Name = '23S Ribosome'
#SS_Goal = '((((((((......((((((((((......((..(((((((((((((......((((((........))).....((((((...(((.......))).......))))))...)))....(((....)))(((((.(....).))))).(((((((((.........))))))))).))...((((((...................))))).).........((....))...(((((.....((.....))....)))))...(((..((((......(((((((((.(((.(((...(((((......)))))........(((.......)))...)))...))).)))))))))...))))........((((((((.........))))))))......(((((......)))))..)))......)).))))))).))...............((....))....)).........((((.....))))...................)))))))))).......((((..(((((......)))))..))))..................((((((....(((((((((((((..(((...((.....))...)))...((....))..((((.....)))).....)))))))))))))..((.....((((((.....((((((((((.((((...((((((......))))))...).)))...(((.(((((........))))))))..).)))))))))...(((.....)))......))))))........))..((((((....(((((....))))).((((((((..((((((((((.....(((...(((.((((...((.((.........))..))...)))).)))..)).).....)))))).)))..)))))))).)...(((((((((........)))))))))....(((......)))...((((.(((...(((......(.((((((...........((..(((((..(((.......(((((.(((..(((.........)))..))).....(..(((......)))).)))))...)))..))))).))...................))))))))))...)))))))((((((((......))))))))....))))))..(((((...(((......((((((((....))))))))...)))..)))))........)))))).......((.....((((((.......))))))((((....((((..((..(((((((...((.....)).))))))......(((.(((.(.(((...(((....)))...)))..))))..(((((........)))))..(((((((((((((...((((....((((..(((..((((((((((((.......).))))))((..((((....(((((((((((.((.....))))))))))..)))....))))...))(..(((((....)))))...))))))...)))...)))).........))))...))....))))))))))).))).))).....((......)).)))).((((.....))))..))))..((((....((((((((.((..(............(((((...............)))))((((((.....(((...((((.....))))...)))...))))))............(((((((((...((.........))...(((((((.....(((....))).......)))))))..((((.(((..(((((((..(((........(((((..((....))...)))))........))))))))..)))))(((((.........)))))....................(((((.......)))))..........))))...)).)))))))....))).)))))))).))))))...........(((((........)))))..((((((((.(((.((......((((.((((((..(((((.(((.(((((.((((((((((...((...............((...((......(.((((((....)))))).)...)).............))......))...))))))))))...(((.((((((.....)))))))))....))))).)))..)))))..(((.......)))((((((...........))))))..((...(((((((...((((((.......)))))).....((......))....)))))))...((((..((((....))))..)))).(((....))).))..........(((((((.((........))))))))).............))))..))))))......((((..(.((((((...((.......))...))))))...).)).).).....((.((.((((((..(((((((((......))))))..))).(((((.....))))).....)))))..)...))..))....(..((((....))).)..)....))..)))))))))))....(((((((...((((..(((((((...............))))))).(((((...((((...(((((((((((....))))))..)))))...)))).)))))...(((....((((.............))))....))).)))).......)))))))(.(((((.....))))).....((..(((((.......)))))....((((((((..((....(((((....)))))...))...))))).))).....))....))))))))).'
#PS_Goal = 'GGUUAAGCGACUAAGCGUACACGGUGGAUGCCCUGGCAGUCAGAGGCGAUGAAGGACGUGCUAAUCUGCGAUAAGCGUCGGUAAGGUGAUAUGAACCGUUAUAACCGGCGAUUUCCGAAUGGGGAAACCCAGUGUGUUUCGACACACUAUCAUUAACUGAAUCCAUAGGUUAAUGAGGCGAACCGGGGGAACUGAAACAUCUAAGUACCCCGAGGAAAAGAAAUCAACCGAGAUUCCCCCAGUAGCGGCGAGCGAACGGGGAGCAGCCCAGAGCCUGAAUCAGUGUGUGUGUUAGUGGAAGCGUCUGGAAAGGCGCGCGAUACAGGGUGACAGCCCCGUACACAAAAAUGCACAUGCUGUGAGCUCGAUGAGUAGGGCGGGACACGUGGUAUCCUGUCUGAAUAUGGGGGGACCAUCCUCCAAGGCUAAAUACUCCUGACUGACCGAUAGUGAACCAGUACCGUGAGGGAAAGGCGAAAAGAACCCCGGCGAGGGGAGUGAAAAAGAACCUGAAACCGUGUACGUACAAGCAGUGGGAGCACGCUUAGGCGUGUGACUGCGUACCUUUUGUAUAAUGGGUCAGCGACUUAUAUUCUGUAGCAAGGUUAACCGAAUAGGGGAGCCGAAGGGAAACCGAGUCUUAACUGGGCGUUAAGUUGCAGGGUAUAGACCCGAAACCCGGUGAUCUAGCCAUGGGCAGGUUGAAGGUUGGGUAACACUAACUGGAGGACCGAACCGACUAAUGUUGAAAAAUUAGCGGAUGACUUGUGGCUGGGGGUGAAAGGCCAAUCAAACCGGGAGAUAGCUGGUUCUCCCCGAAAGCUAUUUAGGUAGCGCCUCGUGAAUUCAUCUCCGGGGGUAGAGCACUGUUUCGGCAAGGGGGUCAUCCCGACUUACCAACCCGAUGCAAACUGCGAAUACCGGAGAAUGUUAUCACGGGAGACACACGGCGGGUGCUAACGUCCGUCGUGAAGAGGGAAACAACCCAGACCGCCAGCUAAGGUCCCAAAGUCAUGGUUAAGUGGGAAACGAUGUGGGAAGGCCCAGACAGCCAGGAUGUUGGCUUAGAAGCAGCCAUCAUUUAAAGAAAGCGUAAUAGCUCACUGGUCGAGUCGGCCUGCGCGGAAGAUGUAACGGGGCUAAACCAUGCACCGAAGCUGCGGCAGCGACGCUUAUGCGUUGUUGGGUAGGGGAGCGUUCUGUAAGCCUGCGAAGGUGUGCUGUGAGGCAUGCUGGAGGUAUCAGAAGUGCGAAUGCUGACAUAAGUAACGAUAAAGCGGGUGAAAAGCCCGCUCGCCGGAAGACCAAGGGUUCCUGUCCAACGUUAAUCGGGGCAGGGUGAGUCGACCCCUAAGGCGAGGCCGAAAGGCGUAGUCGAUGGGAAACAGGUUAAUAUUCCUGUACUUGGUGUUACUGCGAAGGGGGGACGGAGAAGGCUAUGUUGGCCGGGCGACGGUUGUCCCGGUUUAAGCGUGUAGGCUGGUUUUCCAGGCAAAUCCGGAAAAUCAAGGCUGAGGCGUGAUGACGAGGCACUACGGUGCUGAAGCAACAAAUGCCCUGCUUCCAGGAAAAGCCUCUAAGCAUCAGGUAACAUCAAAUCGUACCCCAAACCGACACAGGUGGUCAGGUAGAGAAUACCAAGGCGCUUGAGAGAACUCGGGUGAAGGAACUAGGCAAAAUGGUGCCGUAACUUCGGGAGAAGGCACGCUGAUAUGUAGGUGAGGUCCCUCGCGGAUGGAGCUGAAAUCAGUCGAAGAUACCAGCUGGCUGCAACUGUUUAUUAAAAACACAGCACUGUGCAAACACGAAAGUGGACGUAUACGGUGUGACGCCUGCCCGGUGCCGGAAGGUUAAUUGAUGGGGUUAGCGCAAGCGAAGCUCUUGAUCGAAGCCCCGGUAAACGGCGGCCGUAACUAUAACGGUCCUAAGGUAGCGAAAUUCCUUGUCGGGUAAGUUCCGACCUGCACGAAUGGCGUAAUGAUGGCCAGGCUGUCUCCACCCGAGACUCAGUGAAAUUGAACUCGCUGUGAAGAUGCAGUGUACCCGCGGCAAGACGGAAAGACCCCGUGAACCUUUACUAUAGCUUGACACUGAACAUUGAGCCUUGAUGUGUAGGAUAGGUGGGAGGCUUUGAAGUGUGGACGCCAGUCUGCAUGGAGCCGACCUUGAAAUACCACCCUUUAAUGUUUGAUGUUCUAACGUUGACCCGUAAUCCGGGUUGCGGACAGUGUCUGGUGGGUAGUUUGACUGGGGCGGUCUCCUCCUAAAGAGUAACGGAGGAGCACGAAGGUUGGCUAAUCCUGGUCGGACAUCAGGAGGUUAGUGCAAUGGCAUAAGCCAGCUUGACUGCGAGCGUGACGGCGCGAGCAGGUGCGAAAGCAGGUCAUAGUGAUCCGGUGGUUCUGAAUGGAAGGGCCAUCGCUCAACGGAUAAAAGGUACUCCGGGGAuAACAGGCUGAUACCGCCCAAGAGUUCAUAUCGACGGCGGUGUUUGGCACCUCGAUGUCGGCUCAUCACAUCCUGGGGCUGAAGUAGGUCCCAAGGGUAUGGCuGUUCGCCAUUUAAAGUGGUACGCGAGCUGGGUUUAGAACGUCGUGAGACAGUUCGGUCCCUAUCUGCCGUGGGCGCUGGAGAACUGAGGGGGGCUGCUCCUAGUACGAGAGGACCGGAGUGGACGCAUCACUGGUGUUCGGGUUGUCAUGCCAAUGGCACUGCCCGGUAGCUAAAUGCGGAAGAGAUAAGUGCUGAAAGCAUCUAAGCACGAAACUUGCCCCGAGAUGAGUUCUCCCUGACCCUUUAAGGGUCCUGAAGGAACGUUGAAGACGACGACGUUGAUAGGCCGGGUGUGUAAGCGCAGCGAUGCGUUGAGCUAACCGGUACUAAUGAACCGUGAGGCUUAACCU'
#LS_Goal = 'ooooxxooxxoxxxooxxooooxooxxxxxoxxoxxxxooooooxoxxxoxxxxxooxxxxxxxxxxxxooxxxxooxxxoxxxxooxxxxoxoooxxoxooxxoxxxooxxooxxxxxxooxxxxxxooooooooooooxoooooooxoooooooooxxxxoxxxxoooooooooxxooxxxxooxoxxxxxxxxxxxoxxxxxxxoxooxxxxxxoxxoxxoxxxxxxoxxxxoxxoxxxxxxoxxxxxoxxxxxoxxoxooxooooooooooooxxoooooooooooooxxoooxxxooooxxxxxxoxooooxxxooxxxoooxxxoxxxoooxxxoooooxxoooooooooooooxoooooooooxxxxooooooooxxxxoxoxxooooooooxxxooooxxxxxxxxxxxxxxooxoooxoxxxxxoooooooxxxxxxxxxxoxoxxxxxxxxxxxxxxxxxxxxoxxxxxxxxooooxxxoxxxoooxxxxxxxoxxxoxxxxxxxoxooooxxooxxoxxoxxxxxxxxooooooooooooooxxxxxxxxxxxxooxxxoxxxoxxxoxxxoxxxxxxoooooooxxxxoxxoxoxxxooxooxxooxxxoxoxoxoxxxxxxoxxoxoxxxxxxxoxoxoooxoxxxxoooooooxxxxxxoxxxxxooxxxxxxxxooxxxooooxxooooxxooooooxxoxoxooooooxxooxooxxxxooxooxoxxxxxxxxooxxoxoxooxxoxoooxxxooxxxxoxoxxoxooxooxoxxxxxooxxxxxxoxoxxxxxxxxoxoxxxxoxxoxooxxxoxxoxxxxooooxxoooxoxooxxoxxxxxoxxxxxxxooooooooxooxoooooooooooooxoooxooooooooxxxxxxooxxxxxoxxooxooxoxxoxooooxxxxxxxxxxoooxxxxxxxxxxxxxxoooxxxxxxxxxooxxoxxoxxoxxoxoxxoooxxxxxoxxxoxxoxoooooxxxxxxxxooxxxxxoxxoooxoooxoooxxxooooxxxxxxxoxxxxxoxooxxxxxxxoxxxxxxxxoxxoxxxxoxoxxxooxxxooooxoxoooxoooxxxxxxxxxxxxoxoxxxxxxxxxxoooooooxxxxxoooxoxoooxxooooooooooooooxxooxxxxoxoxxxxxooxoxxxxooxxxoxxxxoooooooxoxxoooooooxxxxxooxxxoxooxxxxxxxxxoxxxoxxxxxxxoxxooxxxoooooxxoxxxxoooooxxxxxxxxxxoxoxxxxoxxxxoooxxoxxxoxxxxxxxxoooxxxxoxxxxooxoxxxxxoooxxxoxxxxxxxxoxxxoooxxxxxoxxxxoooxxxxxxxxoooxxxxxoooooooooxxoxxxxxooxxxxxoxoxoxxoxxooxoooxxoooxxoxxxxoxooooxxoooxxooooxxxxooooooooooxooxoxxxxxoxooooooooooooxxxxooooxoooooxooooooooooooooooxxoooxooxxxoxxooxoxoxxoxxxxxxxooxxxoxoxooxxxoooooooooxxooxxxxxxxxxxxxxxxxxoxxxoxoxxoxxxxxxxxxxxoxxxxxxxxoxoxxxoxooooxxooxxxxxxxxoxxxxxxoxxxoooxxxxxxxxoxxxxxxxxoooxoxxoooxoxxxoxxoxxooooooooxooooxxoxxoxxxoooxxooxxxoooxxoxxoooooooxxxxxxxxxxoxxxxxxxxxxxxxxoxxxxxxxoxxxoxxxxoxxxxxxxxxoxxxxxxooxxxoxxxooxooooxoxoooxxxxxxxxooooxoooooxoooooooxooooxxxxxxxxoooxoooooxxoxxooooooxxxxoxxxxoooooxxxxxxxxxxxxxxxxxxxxxoxxoxxxxxxxoxxoxooxxxxxxxoxxooxxxxxxooooooooxxxxxxxooxxooooxxoxoxoxxxxxxoxxxxxxoxxxxxxxxxxxxoxxxoxxxoxxooxooxxooooxxoxxxoxxxoxxxxxoxxxooxooxxxooxoxxoooooooooxoxoooxoxooxoxxxxoxoooxoxoooooxxxoxoooooxxooxxoooooxoxxxooxooooxxoxoxoooooxooxoooxoxoooooooooxxxxxoooxooxxooxxxxoxxooxooxxxoxoxooxxxooxxooxxxxxoooxxxoooxooooxxxxxoxxxooxxxxxxxxxxooxxxoxxxxxooooxxxoooxoxxooooooxoxoooxxxxxxxxxxxxxxxxoxxooooxxxxxxoxxxxxxoooxxxxoooxxxxxxoxxoxxxxxxoxxxxxxxxxoxxxxoxooooxoooxoxxxxxxooxooooxoxoxxooxxxxxxxxxxxxxoxxoxxxxxxxxxxxxxxoxoxxxxxxxxxoxooxxoxoxxxxxxxxxoxxxoxxxxxoxxxoxxoxxoxxxxxxxxxxxxxxxooxxxxxxooxxooxxxxxxxxxxxoxoxooxxoxxxxxxxxxxxxxooxxxxxoxxxoooxxxxxxxoxxxxxxoxoxxxxxxoxooxxxooooxxoxxxxxoxxxxxooxxxxooooxxoooooooxxxxxxxoxxxxxxxoooooooxooooxxxxxxxxxxxxxxxxxxxooxxxxoxooxxxxoxxxxxxxxxxxxxxooooxoxoooxxxxooxxxxxxxxxxxxxxxxxooxxxxoooxooooxxxxxxxxooxxxxxxoooooooooxooooooxoxxooxxxxxoooxxxxxxooxxxooxxxxxxoooooxxxxxoxoooooxoxxoooooxxxxxxoxooooxxxxxxxxoxooxxoxxooxxoooooo'
# #23S 05/08/2019
# LS_Goal = 'ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooxxxoooooooooooooooooooooxxxooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooxoxxxxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxoooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooxxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooxoooooooxoooooooooooooooooooooooooooooooooooooooooxxoxxxooooooooooooooooooooooooooooxoooooooooooooooooooooooooxxxoxoooooooooooooooooxxxxoooooooooooooooooxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxxxooooooooooooooooooooooooooooooooooooooooooooooxoooooooooooooooooooooooooxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo'
# IUPAC_Goal = 'RRUYARGYRRHBAAGBGYAYRHGGYRRAUGCCYDGGCRRWVASAGGCGAWRAARGRCGURNDWDBBKRCGAWAASBBNNGRBVAGBYRRBADNRDVCNNWNNNNNCNNVSAUNYYYGAAURGGRVAAYCCRVYNNNNNUHRNNNNRBYWWYDHNHNVBNRAUHCAUMRBNDNDHRRRGSDAASSNRGDRAASUGAAACAUCUHAGUABYYNBAGGARMRGAAAUCAAYHGAKAUUYCSNHAGUAGYGGCGARCGAAMVBGRANNAGYCHNGARCCUGAAUCAGYRKRUGUGUUARNDRAABSRUYUGGAAARKYVMRCSRDASHRRGUGABADYCYBGUANNYAAAAAUGCACAURCUGUGAGCUCRMHRARUARRDCGRVRCACGWGDHAYBYUGWYUGAANAWRGGGGGMCCAUCCUCYAAGRCUAAAUACUMSUBWYYGACCGAUAGYGAACHAGUACYGURARGVAARGKBRAAAAGAACCSCKGHDAGGGSAGUGAAAHAGAWMCURAAACYBBRURCVUACAAGCWGURGRAGYVNNNUUAGNBNKGYGACUGCGUACCUUUUGUAUMAUSGGUCAGCGASUURYWYDYHGURGCRAGSUUAABCRHVUAGSGDAGSCGNARVRAAABCGAGUYYKAAHHRRGCRHUAAGUYKCDRBVWRYASACCSRAMMCSNRRYGAUCUABYYAUGRBCAKGDWGRRKGYNRRGUAAHAYYDRCUGRAGGDCCGAMCYSACKNHYGUKRMAARRBBMGSGGAUGAVHUGUGRMUVGGRGUGAAAGRCYAAWCAARYYNGGWGAUAKCUGGUUCUCCYCGAAAKCUAUUKAGGUAGMGCSUHNNRNDHWNRYYNNNSGRGGUAGAGCWCUGUUWNGRYHAKRGGKYYWBMCCGVMYURBSRANYCNWKGCAAACUVCRAAUACBNNNRRRYDHNDDYNYRGSAGWCABWCDRCGGKUGMUAASSWYCGUNGUSRARAGGRWRAVRRYCCAKAYCGHCRGMUMRSRNCYCVARRUYNHDRYUMAGUGGKAAACGAWGUGGGAARGCHYAVACARCYAGGABSUUKGCYUAGAMGCAGCCAHCMUUWAAAGAAAGCSUAAUAGCUCACURGWCRAGUYRKYCYGCGCGGAAGAUDUAACGGGGYWAARYHDNRYRCCRAAGCYRCGGCAGCGACRCUUAUGCGUUGUUGGGUAGRGGAGCGUUSKGUAMGBSDDHGAAGRKNNNYYGDRARRBNKRYUGGASVUAUCMSAAGUGCGAAUGCUGACRURAGUARCGAYAADRBRDGUGAAAWVCHYVYHCGCCGDAARHCYAAGGDUUYCWGYBCAAMGUYAAUCKRVGCWGRGUDAGYCGRYHCCUAAKRYRAGGCHGWRRDGCGUARHYRAUGGRWADYNGGUUAAUAKUCCNRHRCUUGGUGUUACUGCGAAGGGGGGACGGAGAAGGCUAUGUUGGCCGGGCGACGGUUGUCCCGGUUUAAGCGUGUAGGCUGGUUUUCCAGGCAAAUCCGGAAAAUCAAGGCUGAGGCGUGAUGACGAGGCACUACGGUGCUGAAGCAACAAAUGCCCUGCUUCCAGGAAAAGCCUCUAAGCAUCAGGUAACAUCAARYCGUACYNNAAACSRACACASGURGDYRGGWHGARWAKWCYMAGGCGCUUGAGAKAMCYYDGSUGAAGGAACUMGGCAAAWURRHRCCGUAACUUMGGRAGAAGGYDYGCYVNYAUGUAGGUGARGUCCCUCGCGGAUGGAGCUGAARNBRGYBRMAGHDAHSMGVYSGCUGSRACUGUUUAHYAAAAACAYRSVACWSUGCDAAVDCGNAAGHBRRMGUAUASKGUSUGAYRCCUGCCCGGUGCYKGAAGGUUAADYRADRRDGUHADMBHMRKHRAAGCWYYDRAHHGAAGCCCCRGUAAACGGCGGCCGUAACUAUAACGGUCCYRWKGUAGYKAMRUWCCUUGUCGGGYAAGUWYSGACCUGCACGAAUGGYRUAAYSAYGGCSRBRCUGUCUCCASCHGRGRSUCAGYRAARWYGAANUYGCHGHKAAGRURCDGYRUWYCCRYGGCWAGACGGAAAGACCCCGUGMACCUUUACURYARCUUDRYAYKGAHCHYYRRNHHBDNHYGUGYAGRAUAGVUGGKAGVCWDWGAARNNNDDRCGCYAGYHNBNNUGGAGBCRDHSKUGAAAUACCABYCUKBNNNNBYYKDKGYUCUMACBHNRNNBHVKNAHHBKRNNHDVRRACMRUGYHWGGYRGGYAGUUUGACUGGGGCGGUCUCCUCCYAAARNGUAACGGAGGAGYRCDAARRUDNVCUMAKMVYGGUYGGAHAUCRBKMRBWKWGURYAAWGGYANAAGBNHGYUUVACUGYGAGMVNBAYRVBKCRAGCAGRURCGAAAGYAGGUCWUAGUGAUCCGGURGUYCUKHAUGGAARGGSCAUCGCUCAACGGAUAAAAGGUACKCYGGGGAUAACAGGCURAUWCCVCCCAAGAGYUCAYAUCGACGGBGGWGUUUGGCACCUCGAUGUCGGCUCAUCDCAUCCUGGRGCUGHAGYNGGUCCCAARGGUAUGGCUGUUCGCCAUUUAAAGHGGUACGYGASCUGGGUUYARAACGUCGUGAGACAGUUYGGUCCCUAUCURYCRUGGRHGHWDGADDWYUGADDRRRKYUGMYYYUAGUASSAGAGGACCRRRKUGRACGHRYYDCUGGUGUWYVGGUUGUBHYGCCARDSGCAYHGCCBGGUAGCUAHRUDCGGHMDNGAUAASYGCUGAAMGCAUMUAAGCRBRARRCBHVYYHHRAGAUDARWHHKCHSKRRVNVHDHRDBNBYHYDDAAGRDNYGUBVNAGACBABVASGUWRAUAGGYNVSRWGUGDARKYDHDRNDWKDHRUKNAGCKRASBNRUACUAAUBRVYCGWGMGRCUURAYYH'


# Substitute_PS_Long = 'GCUGCGAAAGCAGC'
# Substitute_SS_Long = '(((((....)))))'
# Substitute_LS_Long = 'oooooooooooooo'
# Substitute_IG_Long = 'SSWSSYNNNSSWSS' #strong opening
# #Substitute_IG_Long = 'YRYRYYYYYRYR' #this would match generic versions of the GCUGCGAAA... hp above


#This the substitute HP length (
Substitute_PS_Long = 'GCAUGCGAAAGCAUGC'
Substitute_SS_Long = '((((((....))))))'
Substitute_LS_Long = 'oooooooooooooooo'
Substitute_IG_Long = 'NNNNNNNNNNNNNNNN'
#Substitute_MN_Long = ['-']*len(Substitute_IG_Long)
Substitute_MN_Long = ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
SubsHP = { 'sequence': Substitute_PS_Long, 'secstruct': Substitute_SS_Long, 'lock': Substitute_LS_Long, 'iupac': Substitute_IG_Long, 'master_numbering': Substitute_MN_Long }

#This is how HPs -> bulges are replaced
GenSub = {'sequence':'A','secstruct':'.','lock':'x','iupac':'A', 'master_numbering': '-'}
